stages:
  - test
  - build
  - release

variables:
  DOCKER_AUTH_CONFIG:  '{"auths": {"10.251.4.79:8083": {"auth": "$DOCKER_AU_CONFIG"}}}'
  CONTAINER_TEST_IMAGE: $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG
  CONTAINER_RELEASE_IMAGE: $CI_REGISTRY_IMAGE:latest
  PACKAGE_PATH: /go/src/gade/srv-gade-point

# A hack to make Golang-in-Gitlab happy
.anchors:
  - &inject-gopath
      mkdir -p $(dirname ${PACKAGE_PATH})
      && ln -s ${CI_PROJECT_DIR} ${PACKAGE_PATH}
      && cd ${PACKAGE_PATH}
      && export GO111MODULE=on
      && export PATH="$PATH:/go/bin"
      && export GOPROXY="http://10.251.4.79:8081/repository/go-group-01/"
      && echo $PATH

test:
  stage: test
  image: 10.251.4.79:8083/golang:1.11
  before_script:
    - *inject-gopath
  script:
    - go mod download
    - go test

build:
  image: 10.251.4.79:8083/docker:latest
  services:
    - name: 10.251.4.79:8083/docker:dind
      command: ["--insecure-registry=10.251.4.79:8083"]
  stage: build
  script:
    - docker login -u $NEXUS_DOCKER_USER -p $NEXUS_DOCKER_PASS 10.251.4.79:8083c
    - docker build --pull -t $CONTAINER_TEST_IMAGE .
    - docker push $CONTAINER_TEST_IMAGE

release:
  image: 10.251.4.79:8083/docker:latest
  services:
    - name: 10.251.4.79:8083/docker:dind
      command: ["--insecure-registry=10.251.4.79:8083"]
  stage: release
  script:
    - docker login -u $NEXUS_DOCKER_USER -p $NEXUS_DOCKER_PASS 10.251.4.79:8083
    - docker tag $CONTAINER_TEST_IMAGE $CONTAINER_RELEASE_IMAGE
    - docker push $CONTAINER_RELEASE_IMAGE
  only:
    - tags
