stages:
  - lint
  - test
  - build

variables:
  DOCKER_AUTH_CONFIG: '{"auths": {"artifactory.pegadaian.co.id:8084": {"auth": "$DOCKER_AU_CONFIG"},"artifactory.pegadaian.co.id:5443": {"auth": "$DOCKER_AU_CONFIG"}}}'
  IMAGE_URL: artifactory.pegadaian.co.id:5443/$CI_PROJECT_PATH:$CI_COMMIT_REF_SLUG
  PACKAGE_PATH: /go/src/gade/srv-gade-point

# A hack to make Golang-in-Gitlab happy
.anchors:
  - &inject-gopath
      mkdir -p $(dirname ${PACKAGE_PATH})
      && ln -s ${CI_PROJECT_DIR} ${PACKAGE_PATH}
      && cd ${PACKAGE_PATH}
      && export GO111MODULE=on
      && export PATH="$PATH:/go/bin"
      && export GOPROXY="https://artifactory.pegadaian.co.id/repository/go-group-01/"
      && cp ssl_certificate.crt /usr/local/share/ca-certificates
      && chmod 644 /usr/local/share/ca-certificates/ssl_certificate.crt && update-ca-certificates

lint:
  image:
    name: artifactory.pegadaian.co.id:8084/golangci/golangci-lint:v1.42.1
    entrypoint: [""]
  stage: lint
  before_script:
    - *inject-gopath
  script:
    - go mod download
    - golangci-lint run
  only:
    - merge_requests

test:
  stage: test
  image: artifactory.pegadaian.co.id:8084/golang:1.16
  before_script:
    - *inject-gopath
  script:
    - go mod download
    - go test

build:
  stage: build
  image: artifactory.pegadaian.co.id:8084/docker:latest
  services:
    - name: artifactory.pegadaian.co.id:8084/docker:dind
      command: ["--insecure-registry=artifactory.pegadaian.co.id:8084"]
  script:
    - docker login -u $NEXUS_DOCKER_USER -p $NEXUS_DOCKER_PASS artifactory.pegadaian.co.id:8084
    - docker build --pull -t $IMAGE_URL .
    - docker login -u $NEXUS_DOCKER_USER -p $NEXUS_DOCKER_PASS artifactory.pegadaian.co.id:5443
    - docker push $IMAGE_URL
