ALTER TABLE referral_transactions
ADD COLUMN trx_amount INTEGER,
ADD COLUMN loan_amount INTEGER,
ADD COLUMN interest_amount INTEGER,
ADD COLUMN trx_id VARCHAR(20),
ADD COLUMN trx_date TIMESTAMP,
ADD COLUMN product_code VARCHAR(20),
ADD COLUMN trx_type SMALLINT NOT NULL DEFAULT 0;