// Code generated by MockGen. DO NOT EDIT.
// Source: gade/srv-gade-point/helper (interfaces: IHelper)

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockIHelper is a mock of IHelper interface.
type MockIHelper struct {
	ctrl     *gomock.Controller
	recorder *MockIHelperMockRecorder
}

// MockIHelperMockRecorder is the mock recorder for MockIHelper.
type MockIHelperMockRecorder struct {
	mock *MockIHelper
}

// NewMockIHelper creates a new mock instance.
func NewMockIHelper(ctrl *gomock.Controller) *MockIHelper {
	mock := &MockIHelper{ctrl: ctrl}
	mock.recorder = &MockIHelperMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIHelper) EXPECT() *MockIHelperMockRecorder {
	return m.recorder
}

// ShowName mocks base method.
func (m *MockIHelper) ShowName() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ShowName")
	ret0, _ := ret[0].(string)
	return ret0
}

// ShowName indicates an expected call of ShowName.
func (mr *MockIHelperMockRecorder) ShowName() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ShowName", reflect.TypeOf((*MockIHelper)(nil).ShowName))
}
